name: json2yaml
description: Dart package to format JSON data to YAML. Supports formatting convetions of pubspec files.
version: 1.0.1
homepage: https://github.com/alexei-sintotski/json2yaml

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^2.0.0
  test: ^1.15.0
  test_coverage: ^0.5.0
  yaml: ^2.2.0
